// Generated by CoffeeScript 1.6.3
define(['/js/views/header.js', '/js/views/main.js', '/js/views/portfolio.js'], function(header, main, portfolio) {
  return {
    'HeaderView': header,
    'MainView': main,
    'PortfolioView': portfolio
  };
});
