// Generated by CoffeeScript 1.6.3
define(['/js/views/header.js', '/js/views/main.js', '/js/views/portfolio.js', '/js/views/sap-erp.js'], function(header, main, portfolio, sapErp) {
  return {
    'HeaderView': header,
    'MainView': main,
    'SapErpView': sapErp,
    'PortfolioView': portfolio
  };
});
