// Generated by CoffeeScript 1.6.3
define(['backbone', 'handlebars', 'appTemplates'], function(Backbone, Handlebars, templates) {
  return Backbone.View.extend({
    template: templates['main'],
    initialize: function() {
      return this.model = {};
    },
    render: function() {
      return this.el = this.template(this.model.toJSON());
    }
  });
});
