// Generated by CoffeeScript 1.6.3
define(['handlebars', 'text!/js/tpl/main.hbs', 'text!/js/tpl/sap-erp.hbs'], function (Handlebars, mainTemplate, sapErpTemplate) {
    return {
        'main': Handlebars["default"].compile(mainTemplate),
        'sapErp': Handlebars["default"].compile(sapErpTemplate)
    };
});
