// Generated by CoffeeScript 1.6.3
define(['handlebars', 'text!/js/tpl/main.hbs', 'text!/js/tpl/sap-erp.hbs', 'text!/js/tpl/portfolio.hbs'], function(Handlebars, mainTemplate, sapErpTemplate, portfolioTemplate) {
  return {
    'main': Handlebars["default"].compile(mainTemplate),
    'sapErp': Handlebars["default"].compile(sapErpTemplate),
    'portfolio': Handlebars["default"].compile(portfolioTemplate)
  };
});
