// Generated by CoffeeScript 1.6.3
define(['backbone', 'jquery', 'appViews'], function(Backbone, $, Views) {
  return Backbone.Router.extend({
    initialize: function() {
      if (App.headerView == null) {
        App.headerView = new Views.HeaderView();
      } else {
        App.headerView.delegateEvents();
      }
      return $('header.content').html(App.headerView.render().el);
    },
    routes: {
      '': 'index',
      'portfolio': 'showPortfolio'
    },
    index: function() {
      if (App.mainView == null) {
        App.mainView = new Views.MainView();
      } else {
        App.mainView.delegateEvents();
      }
      return $('main.content > .container').html(App.mainView.render().el);
    },
    showPortfolio: function() {
      if (App.portfolioView == null) {
        App.portfolioView = new Views.PortfolioView();
      } else {
        App.portfolioView.delegateEvents();
      }
      return $('main.content > .container').html(App.portfolioView.render().el);
    }
  });
});
