// Generated by CoffeeScript 1.6.3
define(['backbone', 'jquery', 'appViews'], function(Backbone, $, Views) {
  return Backbone.Router.extend({
    initialize: function() {
      App.headerView = new Views.HeaderView({
        el: 'header.content'
      });
      App.headerView.render();
      return App.headerView.delegateEvents();
    },
    routes: {
      '': 'index',
      'portfolio': 'showPortfolio',
      'sap-erp': 'showSapErp'
    },
    index: function() {
      if (App.mainView == null) {
        App.mainView = new Views.MainView();
      } else {
        App.mainView.delegateEvents();
      }
      return $('main.content > .container').html(App.mainView.render().el);
    },
    showPortfolio: function() {
      if (App.portfolioView == null) {
        App.portfolioView = new Views.PortfolioView();
      } else {
        App.portfolioView.delegateEvents();
      }
      return $('main.content > .container').html(App.portfolioView.render().el);
    },
    showSapErp: function() {
      if (App.sapErpView == null) {
        App.sapErpView = new Views.SapErpView();
      } else {
        App.sapErpView.delegateEvents();
      }
      return $('main.content > .container').html(App.sapErpView.render().el);
    }
  });
});
