// Generated by CoffeeScript 1.6.3
define(['handlebars', 'text!/js/templates/main.hbs', 'text!/js/templates/sap-erp.hbs'], function(Handlebars, mainTemplate, sapErpTemplate) {
  return {
    'main': mainTemplate,
    'sapErp': Handlebars["default"].compile(sapErpTemplate)
  };
});
