// Generated by CoffeeScript 1.6.3
(function(root) {
  if (root.App == null) {
    root.App = {};
  }
  require.config({
    paths: {
      'jquery': '/vendors/jquery/dist/jquery',
      'handlebars': '/vendors/handlebars/handlebars.amd',
      'underscore': '/vendors/underscore/underscore',
      'backbone': '/vendors/backbone/backbone',
      'bootstrap': '/vendors/bootstrap/dist/js/bootstrap',
      'text': '/vendors/requirejs-text/text'
    },
    shim: {
      'backbone': {
        'deps': ['underscore', 'jquery']
      },
      'handlebars': {
        'deps': ['jquery', 'text']
      },
      'bootstrap': {
        'deps': ['jquery']
      }
    },
    waitSeconds: 20
  });
  return require(['jquery'], function($) {
    App.$ = jQuery;
    console.log("Hello, World!");
    App.$(document).ready(function() {
      console.log("Hello, World from jQuery");
      return App.$('#hello-p').append('Hello, World from jQuery');
    });
  });
})(this);
